pub static PHRASES: &[&str] = &[
	"at a grocery store",
	"at a university",
	"at the beach",
	"at the pool",
	"beneath the night sky",
	"by a cliff",
	"by a lake",
	"by a stream",
	"in a basement",
	"in a cave",
	"in a desert",
	"in a dungeon",
	"in a forest",
	"in a greenhouse",
	"in a hospital",
	"in a kitchen",
	"in a library",
	"in a movie theater",
	"in a palace",
	"in a park",
	"in a pet shop",
	"in a pizzeria",
	"in a prison",
	"in a pyramid",
	"in a rainstorm",
	"in a school",
	"in a submarine",
	"in a temple",
	"in a trinket shop",
	"in a warehouse",
	"in a wasteland",
	"in a zoo",
	"in an alley",
	"in front of a sunrise",
	"in front of a sunset",
	"in front of a waterfall",
	"in outer space",
	"in the clouds",
	"on a mountain",
	"on a ranch",
	"on a yacht",
	"on another planet",
	"under a bridge",
	"under a tree",
];
